### PR TITLE
chore(deps): update app-runtime to latest

### PR DESCRIPTION
**Pull request by ghost**
https://jira.dhis2.org/browse/LIBS-200. Updating to the new app-runtime release.

### CODE REVIEW

**Comment by martinkrulltott** [comment]
Lint errors should be resolved by just using `@dhis2/ui` instead of `@dhis2/ui-core`, right?
```
/home/runner/work/analytics/analytics/.storybook/preview.js
Error:   1:26  error  Unable to resolve path to module '@dhis2/ui-core'  import/no-unresolved

/home/runner/work/analytics/analytics/src/components/FileMenu/FileMenu.js
Error:   21:8  error  Unable to resolve path to module '@dhis2/ui-core'  import/no-unresolved
```

**Comment by ghost** [comment]
> Lint errors should be resolved by just using `@dhis2/ui` instead of `@dhis2/ui-core`, right?
> 
> ```
> /home/runner/work/analytics/analytics/.storybook/preview.js
> Error:   1:26  error  Unable to resolve path to module '@dhis2/ui-core'  import/no-unresolved
> 
> /home/runner/work/analytics/analytics/src/components/FileMenu/FileMenu.js
> Error:   21:8  error  Unable to resolve path to module '@dhis2/ui-core'  import/no-unresolved
> ```

Ah, yeah I assume so. I'll update it.

**Review by varl — APPROVED** [review]
Looks good to me.

**Comment by ghost** [comment]
> Looks good to me.

Shall I wait for @dhis2/team-analytics to take a look at this as well, or are we good with merging this?

**Comment by varl** [comment]
We should wait for @dhis2/team-analytics so the timing will be good for them.

**Review by martinkrulltott — APPROVED** [review]
LGTM. Thanks for the contribution. We'll hold the merge a bit until we can time it right with the apps and the pending 2.37 release.

**Comment by ghost** [comment]
> LGTM. Thanks for the contribution. We'll hold the merge a bit until we can time it right with the apps and the pending 2.37 release.

Thanks, sounds good 👍. I'll leave the merge to team analytics then.

**Comment by ghost** [comment]
By the way, once this has been merged, this PR: https://github.com/dhis2/data-visualizer-app/pull/1879 updates app-runtime and related libs for the data-visualizer. That would then also need the new analytics version.

**Review by janhenrikoverland — APPROVED** [review]

**Comment by janhenrikoverland** [comment]
Superseded by https://github.com/dhis2/analytics/pull/1223

**Pull request closed without merging**
