### PR TITLE
feat: add PivotTable component and PivotTableEngine utility

### PR DESCRIPTION
**Pull request by amcgee**
For now I've implemented PivotTable outside of Visualization, since doing the visualization pre-processing would negate a lot of the memory footprint gains of the new engine (we should eventually apply those same improvements to Charts)

TODO (for this PR)
- [x] Ensure compatible API response format
- [ ] Tests
- [x] Example app / Storybook ?
- [x] Factor PivotTable React components

TODO (later)
- [ ] Factor and document `PivotTableEngine`
- [ ] Consolidate with Charts / SingleValue
- [ ] Move to building with app-platform (should be possible now)

### CODE REVIEW

**Comment by amcgee** [comment]
Note: we may want to publish this under a `beta` tag (AKA not merge it to the master branch) since the implementation may change in the future (to consolidate with the Charts API entrypoint)

**Comment by amcgee** [comment]
I've published this branch as `@dhis2/analytics@3.0.0-alpha.0` under the tag `pivot-table-alpha`, so it can be installed for testing or temporarily added to `data-visualizer`

**Comment by amcgee** [comment]
See #264 for potential refactor (to merge into this branch)

**Review by janhenrikoverland — APPROVED** [review]
Thanks @amcgee, looks good so far. Merging now to get the new engine into DV master.

**Pull request merged**
