### PR TITLE
refactor: move pivot table to a multi-component layout

### PR DESCRIPTION
**Pull request by amcgee**
This is a potential refactor into multiple components, for feedback on improved cleanliness and readability.  Does this make the logic more clear or less clear?

### CODE REVIEW

**Comment by amcgee** [comment]
Previous version here, now split into multiple component files
https://github.com/dhis2/analytics/blob/feat/pivot-table/src/components/PivotTable/PivotTable.js

**Comment by amcgee** [comment]
Would recommend looking at the [source](https://github.com/dhis2/analytics/tree/refactor/pivot-table-multicomponent/src/components/PivotTable) rather than the diff

**Comment by edoardo** [comment]
I prefer the split version.
We'll probably need to expand PivotTable.js further for supporting various features, so it can quickly become too big and cumbersome to work with.

**Review by edoardo — APPROVED** [review]
LGTM

**Pull request merged**
